// User
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';

export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGOUT = 'LOGOUT';

// Mark events
export const UPDATE_MARK_LIST = 'UPDATE_MARK_LIST';

// Login Form
export const UPDATE_LOGIN_FORM_NAME = 'UPDATE_LOGIN_FORM_NAME';
export const UPDATE_LOGIN_FORM_EMAIL = 'UPDATE_LOGIN_FORM_EMAIL';
export const UPDATE_LOGIN_FORM_VERIFICATION_CODE = 'UPDATE_LOGIN_FORM_VERIFICATION_CODE';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const LOGIN_FORM_ERROR = 'LOGIN_FORM_ERROR';
export const LOGIN_FORM_ERROR_INVALID_CODE = 'LOGIN_FORM_ERROR_INVALID_CODE';

// Starred Locations
export const ADD_STARRED_LOCATION = 'ADD_STARRED_LOCATION';

// API
export const API_REQUEST = 'API_REQUEST';
export const API_RESPONSE = 'API_RESPONSE';
