// User
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';

export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGOUT = 'LOGOUT';

// Mark events
export const UPDATE_MARK_LIST = 'UPDATE_MARK_LIST';
export const UPDATE_FAVORITE_MARKS = 'UPDATE_FAVORITE_MARKS';
export const FAVORITE_MARK_SUCCESS = 'FAVORITE_MARK_SUCCESS';
export const FAVORITE_MARK_FAILED = 'FAVORITE_MARK_FAILED';
export const UNFAVORITE_MARK_SUCCESS = 'UNFAVORITE_MARK_SUCCESS';
export const UNFAVORITE_MARK_FAILED = 'UNFAVORITE_MARK_FAILED';

// Login Form
export const UPDATE_LOGIN_FORM_NAME = 'UPDATE_LOGIN_FORM_NAME';
export const UPDATE_LOGIN_FORM_EMAIL = 'UPDATE_LOGIN_FORM_EMAIL';
export const UPDATE_LOGIN_FORM_VERIFICATION_CODE = 'UPDATE_LOGIN_FORM_VERIFICATION_CODE';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const LOGIN_FORM_ERROR = 'LOGIN_FORM_ERROR';
export const LOGIN_FORM_ERROR_INVALID_CODE = 'LOGIN_FORM_ERROR_INVALID_CODE';

// Starred Locations
export const ADD_STARRED_LOCATION = 'ADD_STARRED_LOCATION';

// API
export const API_REQUEST = 'API_REQUEST';
export const API_RESPONSE = 'API_RESPONSE';
